### PR TITLE
Publish to Scala 2.13.1

### PR DESCRIPTION
**Pull request by xplosunn**

### CODE REVIEW

**Comment by ghostbuster91** [comment]
Hi, thanks for the PR, but is this really needed? Isn't scala 2.13.0 binary compatible with 2.13.1?

**Comment by xplosunn** [comment]
My bad, then. Changed to just bump the version. You can merge or close.

**Comment by ghostbuster91** [comment]
Can you also update scala version in `.travis.yaml` ?

**Comment by ghostbuster91** [comment]
It looks like we first need to fix neme-plugin for 2.13.1. I will create an issue for that.

**Pull request merged**
