### PR TITLE
Add missing instance import

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by adamw** [comment]
Thx :)

**Comment by kubukoz** [comment]
To be honest I'd consider making that import redundant, e.g. by extending the instances in Diff's companion. Local instances / instances in companion objects of case classes should still have priority, right?

**Comment by adamw** [comment]
@kubukoz yes you are right, I guess we can do simply `object Diff extends DiffInstances`. @ghostbuster91 or was there another reason to have this separate?

**Comment by ghostbuster91** [comment]
@adamw I cannot recall any. This seems like a good idea, let me try implementing it

**Pull request merged**
